server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html index.htm;

    add_header X-Debug-Status "My-Custom-Config-Is-Workinggg";

    # Phục vụ giao diện React
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 🔥 ĐÂY LÀ CHÂN LÝ: Bắt toàn bộ request có chữ /api/ đẩy qua Backend
    location /api/ {
        # Đẩy thẳng vào IP và Cổng của Gateway
        proxy_pass http://35.240.156.187:8080/api/;
        
        # Giữ lại thông tin header cơ bản
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Tối ưu hóa Cache cho ảnh, css, js
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 30d;
        add_header Cache-Control "public";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}