# ===== SonarCloud =====
sonar.projectKey=tienvybui05_kcpm
sonar.organization=tienvybui05
sonar.host.url=https://sonarcloud.io

# ===== Source =====
sonar.sources=backend

# Không phân tích frontend, tool-test
sonar.exclusions=frontend/**,tool-test/**

# ===== Java binaries =====
sonar.java.binaries=backend/**/target/classes

# ===== JaCoCo reports =====
sonar.coverage.jacoco.xmlReportPaths=\
backend/battery-service/target/site/jacoco/jacoco.xml,\
backend/user-service/target/site/jacoco/jacoco.xml,\
backend/subscription-service/target/site/jacoco/jacoco.xml,\
backend/station-service/target/site/jacoco/jacoco.xml,\
backend/transaction-service/target/site/jacoco/jacoco.xml,\
backend/feedback-service/target/site/jacoco/jacoco.xml