spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql_transaction}:${DB_PORT:3306}/${DB_NAME:transaction_service}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8085